### ISSUE TITLE
Any package managers

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [soffes/MarkdownKit#9]
Hey, I really cool to see a package like this. Saw some GitHub MD features and realized it's being developed by GitHub staff; super cool.

Anyways, is there going to be support for Cocoapods or Carthage in the near future? Or am I missing something? I assume so since the example shows an import statement (at least for iOS), but is this currently in early development phase?

Thanks and cheers!

**Comment by soffes** [comment]
Thanks for the question. I don't have any plans to support the others since I'm not using those in my projects or with GitHub (we use SPM at GitHub).

If you want to PR something though, I'm happy to take a look.
